/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.infobird.spark.parquet.entity;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class HiveUser extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HiveUser\",\"namespace\":\"com.infobird.spark.parquet.entity\",\"fields\":[{\"name\":\"telphone_name\",\"type\":\"string\"},{\"name\":\"cityname_name\",\"type\":\"string\"},{\"name\":\"haoduan_name\",\"type\":\"string\"},{\"name\":\"ispname_name\",\"type\":\"string\"},{\"name\":\"completetime_name\",\"type\":\"string\"},{\"name\":\"status_name\",\"type\":\"string\"},{\"name\":\"ringing_duration_name\",\"type\":\"string\"},{\"name\":\"talking_time_name\",\"type\":\"string\"},{\"name\":\"questionidanswerid_name\",\"type\":\"string\"},{\"name\":\"taskid\",\"type\":\"string\"},{\"name\":\"huashuid\",\"type\":\"string\"},{\"name\":\"free2\",\"type\":\"string\"},{\"name\":\"updatetimestamp\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence telphone_name;
  @Deprecated public java.lang.CharSequence cityname_name;
  @Deprecated public java.lang.CharSequence haoduan_name;
  @Deprecated public java.lang.CharSequence ispname_name;
  @Deprecated public java.lang.CharSequence completetime_name;
  @Deprecated public java.lang.CharSequence status_name;
  @Deprecated public java.lang.CharSequence ringing_duration_name;
  @Deprecated public java.lang.CharSequence talking_time_name;
  @Deprecated public java.lang.CharSequence questionidanswerid_name;
  @Deprecated public java.lang.CharSequence taskid;
  @Deprecated public java.lang.CharSequence huashuid;
  @Deprecated public java.lang.CharSequence free2;
  @Deprecated public java.lang.CharSequence updatetimestamp;

  /**
   * Default constructor.
   */
  public HiveUser() {}

  /**
   * All-args constructor.
   */
  public HiveUser(java.lang.CharSequence telphone_name, java.lang.CharSequence cityname_name, java.lang.CharSequence haoduan_name, java.lang.CharSequence ispname_name, java.lang.CharSequence completetime_name, java.lang.CharSequence status_name, java.lang.CharSequence ringing_duration_name, java.lang.CharSequence talking_time_name, java.lang.CharSequence questionidanswerid_name, java.lang.CharSequence taskid, java.lang.CharSequence huashuid, java.lang.CharSequence free2, java.lang.CharSequence updatetimestamp) {
    this.telphone_name = telphone_name;
    this.cityname_name = cityname_name;
    this.haoduan_name = haoduan_name;
    this.ispname_name = ispname_name;
    this.completetime_name = completetime_name;
    this.status_name = status_name;
    this.ringing_duration_name = ringing_duration_name;
    this.talking_time_name = talking_time_name;
    this.questionidanswerid_name = questionidanswerid_name;
    this.taskid = taskid;
    this.huashuid = huashuid;
    this.free2 = free2;
    this.updatetimestamp = updatetimestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return telphone_name;
    case 1: return cityname_name;
    case 2: return haoduan_name;
    case 3: return ispname_name;
    case 4: return completetime_name;
    case 5: return status_name;
    case 6: return ringing_duration_name;
    case 7: return talking_time_name;
    case 8: return questionidanswerid_name;
    case 9: return taskid;
    case 10: return huashuid;
    case 11: return free2;
    case 12: return updatetimestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: telphone_name = (java.lang.CharSequence)value$; break;
    case 1: cityname_name = (java.lang.CharSequence)value$; break;
    case 2: haoduan_name = (java.lang.CharSequence)value$; break;
    case 3: ispname_name = (java.lang.CharSequence)value$; break;
    case 4: completetime_name = (java.lang.CharSequence)value$; break;
    case 5: status_name = (java.lang.CharSequence)value$; break;
    case 6: ringing_duration_name = (java.lang.CharSequence)value$; break;
    case 7: talking_time_name = (java.lang.CharSequence)value$; break;
    case 8: questionidanswerid_name = (java.lang.CharSequence)value$; break;
    case 9: taskid = (java.lang.CharSequence)value$; break;
    case 10: huashuid = (java.lang.CharSequence)value$; break;
    case 11: free2 = (java.lang.CharSequence)value$; break;
    case 12: updatetimestamp = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'telphone_name' field.
   */
  public java.lang.CharSequence getTelphoneName() {
    return telphone_name;
  }

  /**
   * Sets the value of the 'telphone_name' field.
   * @param value the value to set.
   */
  public void setTelphoneName(java.lang.CharSequence value) {
    this.telphone_name = value;
  }

  /**
   * Gets the value of the 'cityname_name' field.
   */
  public java.lang.CharSequence getCitynameName() {
    return cityname_name;
  }

  /**
   * Sets the value of the 'cityname_name' field.
   * @param value the value to set.
   */
  public void setCitynameName(java.lang.CharSequence value) {
    this.cityname_name = value;
  }

  /**
   * Gets the value of the 'haoduan_name' field.
   */
  public java.lang.CharSequence getHaoduanName() {
    return haoduan_name;
  }

  /**
   * Sets the value of the 'haoduan_name' field.
   * @param value the value to set.
   */
  public void setHaoduanName(java.lang.CharSequence value) {
    this.haoduan_name = value;
  }

  /**
   * Gets the value of the 'ispname_name' field.
   */
  public java.lang.CharSequence getIspnameName() {
    return ispname_name;
  }

  /**
   * Sets the value of the 'ispname_name' field.
   * @param value the value to set.
   */
  public void setIspnameName(java.lang.CharSequence value) {
    this.ispname_name = value;
  }

  /**
   * Gets the value of the 'completetime_name' field.
   */
  public java.lang.CharSequence getCompletetimeName() {
    return completetime_name;
  }

  /**
   * Sets the value of the 'completetime_name' field.
   * @param value the value to set.
   */
  public void setCompletetimeName(java.lang.CharSequence value) {
    this.completetime_name = value;
  }

  /**
   * Gets the value of the 'status_name' field.
   */
  public java.lang.CharSequence getStatusName() {
    return status_name;
  }

  /**
   * Sets the value of the 'status_name' field.
   * @param value the value to set.
   */
  public void setStatusName(java.lang.CharSequence value) {
    this.status_name = value;
  }

  /**
   * Gets the value of the 'ringing_duration_name' field.
   */
  public java.lang.CharSequence getRingingDurationName() {
    return ringing_duration_name;
  }

  /**
   * Sets the value of the 'ringing_duration_name' field.
   * @param value the value to set.
   */
  public void setRingingDurationName(java.lang.CharSequence value) {
    this.ringing_duration_name = value;
  }

  /**
   * Gets the value of the 'talking_time_name' field.
   */
  public java.lang.CharSequence getTalkingTimeName() {
    return talking_time_name;
  }

  /**
   * Sets the value of the 'talking_time_name' field.
   * @param value the value to set.
   */
  public void setTalkingTimeName(java.lang.CharSequence value) {
    this.talking_time_name = value;
  }

  /**
   * Gets the value of the 'questionidanswerid_name' field.
   */
  public java.lang.CharSequence getQuestionidansweridName() {
    return questionidanswerid_name;
  }

  /**
   * Sets the value of the 'questionidanswerid_name' field.
   * @param value the value to set.
   */
  public void setQuestionidansweridName(java.lang.CharSequence value) {
    this.questionidanswerid_name = value;
  }

  /**
   * Gets the value of the 'taskid' field.
   */
  public java.lang.CharSequence getTaskid() {
    return taskid;
  }

  /**
   * Sets the value of the 'taskid' field.
   * @param value the value to set.
   */
  public void setTaskid(java.lang.CharSequence value) {
    this.taskid = value;
  }

  /**
   * Gets the value of the 'huashuid' field.
   */
  public java.lang.CharSequence getHuashuid() {
    return huashuid;
  }

  /**
   * Sets the value of the 'huashuid' field.
   * @param value the value to set.
   */
  public void setHuashuid(java.lang.CharSequence value) {
    this.huashuid = value;
  }

  /**
   * Gets the value of the 'free2' field.
   */
  public java.lang.CharSequence getFree2() {
    return free2;
  }

  /**
   * Sets the value of the 'free2' field.
   * @param value the value to set.
   */
  public void setFree2(java.lang.CharSequence value) {
    this.free2 = value;
  }

  /**
   * Gets the value of the 'updatetimestamp' field.
   */
  public java.lang.CharSequence getUpdatetimestamp() {
    return updatetimestamp;
  }

  /**
   * Sets the value of the 'updatetimestamp' field.
   * @param value the value to set.
   */
  public void setUpdatetimestamp(java.lang.CharSequence value) {
    this.updatetimestamp = value;
  }

  /** Creates a new HiveUser RecordBuilder */
  public static com.infobird.spark.parquet.entity.HiveUser.Builder newBuilder() {
    return new com.infobird.spark.parquet.entity.HiveUser.Builder();
  }
  
  /** Creates a new HiveUser RecordBuilder by copying an existing Builder */
  public static com.infobird.spark.parquet.entity.HiveUser.Builder newBuilder(com.infobird.spark.parquet.entity.HiveUser.Builder other) {
    return new com.infobird.spark.parquet.entity.HiveUser.Builder(other);
  }
  
  /** Creates a new HiveUser RecordBuilder by copying an existing HiveUser instance */
  public static com.infobird.spark.parquet.entity.HiveUser.Builder newBuilder(com.infobird.spark.parquet.entity.HiveUser other) {
    return new com.infobird.spark.parquet.entity.HiveUser.Builder(other);
  }
  
  /**
   * RecordBuilder for HiveUser instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HiveUser>
    implements org.apache.avro.data.RecordBuilder<HiveUser> {

    private java.lang.CharSequence telphone_name;
    private java.lang.CharSequence cityname_name;
    private java.lang.CharSequence haoduan_name;
    private java.lang.CharSequence ispname_name;
    private java.lang.CharSequence completetime_name;
    private java.lang.CharSequence status_name;
    private java.lang.CharSequence ringing_duration_name;
    private java.lang.CharSequence talking_time_name;
    private java.lang.CharSequence questionidanswerid_name;
    private java.lang.CharSequence taskid;
    private java.lang.CharSequence huashuid;
    private java.lang.CharSequence free2;
    private java.lang.CharSequence updatetimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(com.infobird.spark.parquet.entity.HiveUser.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.infobird.spark.parquet.entity.HiveUser.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing HiveUser instance */
    private Builder(com.infobird.spark.parquet.entity.HiveUser other) {
            super(com.infobird.spark.parquet.entity.HiveUser.SCHEMA$);
      if (isValidValue(fields()[0], other.telphone_name)) {
        this.telphone_name = data().deepCopy(fields()[0].schema(), other.telphone_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cityname_name)) {
        this.cityname_name = data().deepCopy(fields()[1].schema(), other.cityname_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.haoduan_name)) {
        this.haoduan_name = data().deepCopy(fields()[2].schema(), other.haoduan_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ispname_name)) {
        this.ispname_name = data().deepCopy(fields()[3].schema(), other.ispname_name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.completetime_name)) {
        this.completetime_name = data().deepCopy(fields()[4].schema(), other.completetime_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status_name)) {
        this.status_name = data().deepCopy(fields()[5].schema(), other.status_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ringing_duration_name)) {
        this.ringing_duration_name = data().deepCopy(fields()[6].schema(), other.ringing_duration_name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.talking_time_name)) {
        this.talking_time_name = data().deepCopy(fields()[7].schema(), other.talking_time_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.questionidanswerid_name)) {
        this.questionidanswerid_name = data().deepCopy(fields()[8].schema(), other.questionidanswerid_name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.taskid)) {
        this.taskid = data().deepCopy(fields()[9].schema(), other.taskid);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.huashuid)) {
        this.huashuid = data().deepCopy(fields()[10].schema(), other.huashuid);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.free2)) {
        this.free2 = data().deepCopy(fields()[11].schema(), other.free2);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.updatetimestamp)) {
        this.updatetimestamp = data().deepCopy(fields()[12].schema(), other.updatetimestamp);
        fieldSetFlags()[12] = true;
      }
    }

    /** Gets the value of the 'telphone_name' field */
    public java.lang.CharSequence getTelphoneName() {
      return telphone_name;
    }
    
    /** Sets the value of the 'telphone_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setTelphoneName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.telphone_name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'telphone_name' field has been set */
    public boolean hasTelphoneName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'telphone_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearTelphoneName() {
      telphone_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'cityname_name' field */
    public java.lang.CharSequence getCitynameName() {
      return cityname_name;
    }
    
    /** Sets the value of the 'cityname_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setCitynameName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.cityname_name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'cityname_name' field has been set */
    public boolean hasCitynameName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'cityname_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearCitynameName() {
      cityname_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'haoduan_name' field */
    public java.lang.CharSequence getHaoduanName() {
      return haoduan_name;
    }
    
    /** Sets the value of the 'haoduan_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setHaoduanName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.haoduan_name = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'haoduan_name' field has been set */
    public boolean hasHaoduanName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'haoduan_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearHaoduanName() {
      haoduan_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ispname_name' field */
    public java.lang.CharSequence getIspnameName() {
      return ispname_name;
    }
    
    /** Sets the value of the 'ispname_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setIspnameName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ispname_name = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ispname_name' field has been set */
    public boolean hasIspnameName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ispname_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearIspnameName() {
      ispname_name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'completetime_name' field */
    public java.lang.CharSequence getCompletetimeName() {
      return completetime_name;
    }
    
    /** Sets the value of the 'completetime_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setCompletetimeName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.completetime_name = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'completetime_name' field has been set */
    public boolean hasCompletetimeName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'completetime_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearCompletetimeName() {
      completetime_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'status_name' field */
    public java.lang.CharSequence getStatusName() {
      return status_name;
    }
    
    /** Sets the value of the 'status_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setStatusName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status_name = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'status_name' field has been set */
    public boolean hasStatusName() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'status_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearStatusName() {
      status_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'ringing_duration_name' field */
    public java.lang.CharSequence getRingingDurationName() {
      return ringing_duration_name;
    }
    
    /** Sets the value of the 'ringing_duration_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setRingingDurationName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.ringing_duration_name = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'ringing_duration_name' field has been set */
    public boolean hasRingingDurationName() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'ringing_duration_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearRingingDurationName() {
      ringing_duration_name = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'talking_time_name' field */
    public java.lang.CharSequence getTalkingTimeName() {
      return talking_time_name;
    }
    
    /** Sets the value of the 'talking_time_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setTalkingTimeName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.talking_time_name = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'talking_time_name' field has been set */
    public boolean hasTalkingTimeName() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'talking_time_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearTalkingTimeName() {
      talking_time_name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'questionidanswerid_name' field */
    public java.lang.CharSequence getQuestionidansweridName() {
      return questionidanswerid_name;
    }
    
    /** Sets the value of the 'questionidanswerid_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setQuestionidansweridName(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.questionidanswerid_name = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'questionidanswerid_name' field has been set */
    public boolean hasQuestionidansweridName() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'questionidanswerid_name' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearQuestionidansweridName() {
      questionidanswerid_name = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'taskid' field */
    public java.lang.CharSequence getTaskid() {
      return taskid;
    }
    
    /** Sets the value of the 'taskid' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setTaskid(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.taskid = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'taskid' field has been set */
    public boolean hasTaskid() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'taskid' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearTaskid() {
      taskid = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'huashuid' field */
    public java.lang.CharSequence getHuashuid() {
      return huashuid;
    }
    
    /** Sets the value of the 'huashuid' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setHuashuid(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.huashuid = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'huashuid' field has been set */
    public boolean hasHuashuid() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'huashuid' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearHuashuid() {
      huashuid = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'free2' field */
    public java.lang.CharSequence getFree2() {
      return free2;
    }
    
    /** Sets the value of the 'free2' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setFree2(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.free2 = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'free2' field has been set */
    public boolean hasFree2() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'free2' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearFree2() {
      free2 = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'updatetimestamp' field */
    public java.lang.CharSequence getUpdatetimestamp() {
      return updatetimestamp;
    }
    
    /** Sets the value of the 'updatetimestamp' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder setUpdatetimestamp(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.updatetimestamp = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'updatetimestamp' field has been set */
    public boolean hasUpdatetimestamp() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'updatetimestamp' field */
    public com.infobird.spark.parquet.entity.HiveUser.Builder clearUpdatetimestamp() {
      updatetimestamp = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    public HiveUser build() {
      try {
        HiveUser record = new HiveUser();
        record.telphone_name = fieldSetFlags()[0] ? this.telphone_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.cityname_name = fieldSetFlags()[1] ? this.cityname_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.haoduan_name = fieldSetFlags()[2] ? this.haoduan_name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ispname_name = fieldSetFlags()[3] ? this.ispname_name : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.completetime_name = fieldSetFlags()[4] ? this.completetime_name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.status_name = fieldSetFlags()[5] ? this.status_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.ringing_duration_name = fieldSetFlags()[6] ? this.ringing_duration_name : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.talking_time_name = fieldSetFlags()[7] ? this.talking_time_name : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.questionidanswerid_name = fieldSetFlags()[8] ? this.questionidanswerid_name : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.taskid = fieldSetFlags()[9] ? this.taskid : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.huashuid = fieldSetFlags()[10] ? this.huashuid : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.free2 = fieldSetFlags()[11] ? this.free2 : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.updatetimestamp = fieldSetFlags()[12] ? this.updatetimestamp : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
